
exports.up = function(knex) {
    return knex.raw(
        `
            CREATE TABLE academicPrograms(
                ap_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                ap_name text not null,
                ap_abbrevation text not null
            );
        `
  )
};

exports.down = function(knex) {
    return knex.raw('DROP TABLE academicProgram')
};
