
exports.up = function(knex) {
    return knex.raw(
        `
          CREATE TABLE students(
              student_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
              first_name text not null,
              last_name text not null,
              birthdate date not null,
              ap_id int not null,
              year_level int not null
          )
        `
    )
};

exports.down = function(knex) {
    return knex.raw('DROP TABLE students')
};
