
exports.up = function(knex) {
    return knex.raw(
        `
            CREATE TABLE memberships(
                membership_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
                student_id int not null,
                org_id int not null
            )
        `
  )
};

exports.down = function(knex) {
  return knex.raw('DROP TABLE memberships')
};
